directly use specified opset version; try CI
Signed-off-by: jcwchen <jacky82226@gmail.com>

diff --git a/.azure-pipelines/Linux-CI.yml b/.azure-pipelines/Linux-CI.yml
--- a/.azure-pipelines/Linux-CI.yml
+++ b/.azure-pipelines/Linux-CI.yml
@@ -135,6 +135,12 @@ jobs:
       python workflow_scripts/test_generated_backend.py
       # onnx.checker all generated backend data
       python onnx/backend/test/cmd_tools.py generate-data
+      git status
+      git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
+      if [ $? -ne 0 ]; then
+        echo "git diff returned failures"
+        exit 1
+      fi
       python workflow_scripts/test_generated_backend.py
 
     displayName: Test backend test data
