int64 for negativeloss and apply Mac CI, exclude .output.pb
Signed-off-by: jcwchen <jacky82226@gmail.com>

diff --git a/.azure-pipelines/MacOS-CI.yml b/.azure-pipelines/MacOS-CI.yml
--- a/.azure-pipelines/MacOS-CI.yml
+++ b/.azure-pipelines/MacOS-CI.yml
@@ -102,4 +102,12 @@ jobs:
         exit 1
       fi
 
+      python onnx/backend/test/cmd_tools.py generate-data
+      git status
+      git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
+      if [ $? -ne 0 ]; then
+        echo "git diff returned failures"
+        exit 1
+      fi
+
     displayName: 'Run ONNX Tests'
