test generation without opencv-python in CIs
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>

diff --git a/.azure-pipelines/MacOS-CI.yml b/.azure-pipelines/MacOS-CI.yml
--- a/.azure-pipelines/MacOS-CI.yml
+++ b/.azure-pipelines/MacOS-CI.yml
@@ -93,4 +93,13 @@ jobs:
         exit 1
       fi
 
+      pip uninstall -y opencv-python
+      python onnx/backend/test/cmd_tools.py generate-data --clean
+      git status
+      git diff --exit-code -- . ':!onnx/onnx-data.proto' ':!onnx/onnx-data.proto3' ':!*output_*.pb' ':!*input_*.pb'
+      if [ $? -ne 0 ]; then
+        echo "git diff for test generation without opencv-python returned failures. Please check updated node test files"
+        exit 1
+      fi
+
     displayName: 'Run ONNX Tests'
