validate the generated number of input.pb and output.pb in CIs
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>

diff --git a/.azure-pipelines/MacOS-CI.yml b/.azure-pipelines/MacOS-CI.yml
--- a/.azure-pipelines/MacOS-CI.yml
+++ b/.azure-pipelines/MacOS-CI.yml
@@ -109,5 +109,10 @@ jobs:
         echo "git diff for test generation returned failures. Please check updated node test files"
         exit 1
       fi
+      git diff --exit-code --name-only -- . ':!onnx/onnx-data.proto' ':!onnx/onnx-data.proto3'
+      if [ $? -ne 0 ]; then
+        echo "Test generation returned failures. Please check the number of node test files (input_*.pb or output_*.pb)"
+        exit 1
+      fi
 
     displayName: 'Run ONNX Tests'
