check generated backend data in CIs
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>

diff --git a/.azure-pipelines/MacOS-CI.yml b/.azure-pipelines/MacOS-CI.yml
--- a/.azure-pipelines/MacOS-CI.yml
+++ b/.azure-pipelines/MacOS-CI.yml
@@ -74,6 +74,13 @@ jobs:
         exit 1
       fi
 
+      # checker.check_model all generated backend data
+      python workflow_scripts\test_generated_backend.py
+      if [ $? -ne 0 ]; then
+        echo "check generated backend data failed"
+        exit 1
+      fi
+
       # Do not hardcode onnx's namespace in the c++ source code, so that
       # other libraries who statically link with onnx can hide onnx symbols
       # in a private namespace.
