Add workflow dispatch option to publish whl to pypi onnx (#6819)
### Description

* Add possibility to publish "release" whl directly to pypi
* no interaction with the github release-function was added.

### Motivation and Context
<!-- - Why is this change required? What problem does it solve? -->
<!-- - If it fixes an open issue, please link to the issue here. -->

---------

Signed-off-by: Andreas Fehlner <fehlner@arcor.de>
Signed-off-by: gramalingam <grama@microsoft.com>

diff --git a/.github/workflows/create_release.yml b/.github/workflows/create_release.yml
--- a/.github/workflows/create_release.yml
+++ b/.github/workflows/create_release.yml
@@ -7,6 +7,7 @@ on:
   schedule:
     # Run weekly on Monday 00:00 UTC
     - cron:  '00 00 * * MON'
+
   push:
     branches: [main, rel-*]
   pull_request:
@@ -39,6 +40,14 @@ on:
           - 'yes'
           - 'no'
         default: 'no'
+      publish_pypi_release:
+        description: 'Caution: Publish to pypi-release'
+        required: true
+        type: choice
+        options:
+          - 'yes'
+          - 'no'
+        default: 'no'
       build_mode:
         description: 'Specify the build mode (release or preview)'
         required: true
@@ -49,7 +58,7 @@ on:
         default: 'preview'
 
 
-permissions:  # set top-level default permissions as security best practice
+permissions:  # set top-level default permissions as security good practice
   contents: read
 
 concurrency:
@@ -93,11 +102,12 @@ jobs:
       os: "win_free"
       build_mode: ${{ github.event.inputs.build_mode || 'preview' }}
 
+
   call-mac:
     if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'run release CIs')
     uses: ./.github/workflows/release_mac.yml
     with:
-      os: "macos"   
+      os: "macos"
       build_mode: ${{ github.event.inputs.build_mode || 'preview' }}
   
   call-sdist:
@@ -106,7 +116,35 @@ jobs:
     with:
       os: "macos"
       build_mode: ${{ github.event.inputs.build_mode || 'preview' }}
-      
+     
+
+  check_for_publish_release_build_to_pypi:
+    name: Check for Publish release build to pypi
+    runs-on: ubuntu-latest
+
+    needs: [call-workflow-ubuntu_x86, call-workflow-ubuntu_aarch64, call-workflow-mac, call-workflow-win, call-workflow-win-freethreading, call-workflow-sdist]
+    if: (!contains(join(needs.*.result, ' '), 'skipped')) && (github.repository_owner == 'onnx') && startsWith(github.ref, 'refs/heads/rel-')
+
+    steps:
+
+      - name: Ensure build mode is release
+        run: |
+          if [ "${{ github.event.inputs.build_mode }}" != "release" ]; then
+            echo "Error: build_mode must be set to 'release' to proceed."
+            exit 1
+          fi
+
+      - name: Check if package_version matches branch
+        run: |
+          branch_version=${GITHUB_REF#refs/heads/rel-}
+          package_version=$(cat VERSION_NUMBER)
+          echo "Branch version: $branch_version"
+          echo "Package version: $package_version"
+          if [ "$branch_version" != "$package_version" ]; then
+            echo "Error: Branch version ($branch_version) does not match package version ($package_version)."
+            exit 1
+          fi
+
 
   check_for_publish_preview_build_to_testpypi_weekly:
     name: Check for Publish preview build to test.pypi-weekly
@@ -162,7 +200,7 @@ jobs:
           print-hash: true
 
   check_for_publish_release_build_to_testpypi:
-    name: Check for Publish release build to test.pypi
+    name: Check for Publish release build to test.pypi (rc-candidates)
     runs-on: ubuntu-latest
 
     needs: [call-ubuntu_x86, call-ubuntu_aarch64, call-mac, call-win_x86, call-win_arm64, call-win-freethreading, call-sdist]
@@ -263,6 +301,41 @@ jobs:
           verbose: true     
           print-hash: true  
 
+
+  publish_release_build_to_pypi:
+    name: Publish release build to pypi
+    runs-on: ubuntu-latest
+    needs: [check_for_publish_release_build_to_pypi]
+
+    environment:
+      name: pypi-release
+      url: https://pypi.org/p/onnx
+
+    permissions:
+      contents: read
+      id-token: write
+
+    steps:
+      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806        
+        with:
+          pattern: wheels*
+          path: dist
+          merge-multiple: true
+
+      - uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806        
+        with:
+          pattern: sdist
+          path: dist
+          merge-multiple: true
+
+      - name: Publish release_build to pypi
+        if: (github.repository_owner == 'onnx')
+        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
+        with:   
+          repository-url: https://upload.pypi.org/legacy/
+          verbose: true     
+          print-hash: true        
+
   test_source_dist:
     name: test source distribution
     needs: [publish_preview_build_to_pypi_weekly, publish_release_build_to_testpypi]
@@ -270,4 +343,3 @@ jobs:
     uses: ./.github/workflows/preview_source_dist_test.yml
     with:
       os: "macos"
-
