update
Signed-off-by: Andreas Fehlner <fehlner@arcor.de>

diff --git a/.github/workflows/create_release.yml b/.github/workflows/create_release.yml
--- a/.github/workflows/create_release.yml
+++ b/.github/workflows/create_release.yml
@@ -119,10 +119,24 @@ jobs:
     if: (!contains(join(needs.*.result, ' '), 'skipped')) && (github.repository_owner == 'onnx') && startsWith(github.ref, 'refs/heads/rel-')
 
     steps:
-      - name: print debug vars
+
+      - name: Ensure build mode is release
         run: |
-          echo "All environment variables:"
-          printenv
+          if [ "${{ github.event.inputs.build_mode }}" != "release" ]; then
+            echo "Error: build_mode must be set to 'release' to proceed."
+            exit 1
+          fi
+
+      - name: Check if package_version matches branch
+        run: |
+          branch_version=${GITHUB_REF#refs/heads/rel-}
+          package_version=$(cat VERSION_NUMBER)
+          echo "Branch version: $branch_version"
+          echo "Package version: $package_version"
+          if [ "$branch_version" != "$package_version" ]; then
+            echo "Error: Branch version ($branch_version) does not match package version ($package_version)."
+            exit 1
+          fi
 
 
   check_for_publish_preview_build_to_testpypi_weekly:
