Update lint.yml to include instructions for when auto-gen files don't match
Signed-off-by: Justin Chu <justinchuby@users.noreply.github.com>

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -98,17 +98,17 @@ jobs:
       - name: Check auto-gen files are up-to-date
         run: |
           echo -e "\n::group:: ===> check auto-gen files are up-to-date..."
-          
           ONNX_ML=1 python onnx/defs/gen_doc.py
           ONNX_ML=0 python onnx/defs/gen_doc.py
           python onnx/gen_proto.py -l
           python onnx/gen_proto.py -l --ml
           python onnx/backend/test/stat_coverage.py
+          echo -e "::endgroup::"
 
+          echo -e "\n::group:: ===> check auto-gen files are up-to-date..."
           git status
-          git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
-          if [ $? -ne 0 ]; then
-            echo "git diff returned failures"
+          if ! git diff --color --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'; then
+            echo -e "\e[1m\e[36mGit diff returned failures. This may mean you need to regenerate the docs or need to update the source code that will generate the documentation.\e[0m"
             exit 1
           fi
           echo -e "::endgroup::"
