try text
Signed-off-by: Chun-Wei Chen <jacky82226@gmail.com>

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -65,25 +65,9 @@ jobs:
           export ONNX_BUILD_TESTS=0
           export ONNX_ML=1
           export CMAKE_ARGS="-DONNXIFI_DUMMY_BACKEND=ON -DONNX_WERROR=ON"
+          export ONNX_NAMESPACE=ONNX_NAMESPACE_FOO_BAR_FOR_CI
 
           python setup.py install
-
-      - name: Check auto-gen files are up-to-date
-        run: |
-          echo -e "\n::group:: ===> check auto-gen files are up-to-date..."
-          python onnx/defs/gen_doc.py
-          python onnx/gen_proto.py -l
-          python onnx/gen_proto.py -l --ml
-          python onnx/backend/test/stat_coverage.py
-
-          git status
-          git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
-          if [ $? -ne 0 ]; then
-            echo "git diff returned failures"
-            exit 1
-          fi
-          echo -e "::endgroup::"
-
       - name: Install dependencies
         run: |
           python -m pip install -r requirements-dev.txt
@@ -111,4 +95,18 @@ jobs:
           sarif_file: lintrunner.sarif
           category: lintrunner
           checkout_path: ${{ github.workspace }}
+      - name: Check auto-gen files are up-to-date
+        run: |
+          echo -e "\n::group:: ===> check auto-gen files are up-to-date..."
+          python onnx/defs/gen_doc.py
+          python onnx/gen_proto.py -l
+          python onnx/gen_proto.py -l --ml
+          python onnx/backend/test/stat_coverage.py
 
+          git status
+          git diff --exit-code -- . ':(exclude)onnx/onnx-data.proto' ':(exclude)onnx/onnx-data.proto3'
+          if [ $? -ne 0 ]; then
+            echo "git diff returned failures"
+            exit 1
+          fi
+          echo -e "::endgroup::"
